#pragma once

void dlDisplay();
void dlCall(uint16_t dest);
void dlJump(uint16_t dest);
void dlBegin(uint8_t primitive);
void dlEnd();
void dlReturn();
void dlMacro(uint8_t m);
void dlNop();
void dlBitmapSource(uint32_t addr);
void dlBitmapHandle(uint8_t handle);
void dlCell(uint8_t cell);
void dlBitmapLayout(uint8_t format, uint16_t lineStride, uint16_t height);
void dlBitmapSize(uint8_t filter, uint8_t wrapX, uint8_t wrapY, uint16_t width, uint16_t height);
void dlBitmapLayoutH(uint16_t lineStride, uint16_t height);
void dlBitmapSizeH(uint16_t width, uint16_t height);
void dlPaletteSource(uint32_t addr);
void dlBitmapExtFormat(uint16_t format);
void dlBitmapSwizzle(uint8_t r, uint8_t g, uint8_t b, uint8_t a);
void dlPointSize(uint16_t size);
void dlLineWidth(uint16_t width);
void dlVertexFormat(uint8_t frac);
void dlVertexTranslateX(int32_t x);
void dlVertexTranslateY(int32_t y);
void dlVertex2f(int16_t x, int16_t y);
void dlVertex2ii(uint16_t x, uint16_t y, uint8_t handle = 0, uint8_t cell = 0);
void dlClearColorRGB(uint8_t r, uint8_t g, uint8_t b);
void dlClearColorRGB(uint32_t rgb);
void dlColorRGB(uint8_t r, uint8_t g, uint8_t b);
void dlColorRGB(uint32_t rgb);
void dlClearColorA(uint8_t a);
void dlColorA(uint8_t a);
void dlClearStencil(uint8_t s);
void dlClearTag(uint8_t tag);
void dlColorMask(bool r, bool g, bool b, bool a);
void dlClear(bool color = true, bool stencil = true, bool tag = true);
void dlAlphaFunc(uint8_t func, uint8_t ref);
void dlStencilFunc(uint8_t func, uint8_t ref, uint8_t mask);
void dlBlendFunc(uint8_t src, uint8_t dst);
void dlStencilOp(uint8_t sfail, uint8_t spass);
void dlStencilMask(uint8_t mask);
void dlTag(uint8_t tag);
void dlTagMask(bool enable);
void dlBitmapTransformA(int32_t a);
void dlBitmapTransformB(int32_t b);
void dlBitmapTransformC(int32_t c);
void dlBitmapTransformD(int32_t d);
void dlBitmapTransformE(int32_t e);
void dlBitmapTransformF(int32_t f);
void dlBitmapTransformA(uint8_t p, int32_t a);
void dlBitmapTransformB(uint8_t p, int32_t b);
void dlBitmapTransformD(uint8_t p, int32_t d);
void dlBitmapTransformE(uint8_t p, int32_t e);
void dlScissorXY(uint16_t x, uint16_t y);
void dlScissorSize(uint16_t width, uint16_t height);
void dlSaveContext();
void dlRestoreContext();